create table location (location_id integer generated by default as identity, location_code varchar(255), location_name varchar(255), primary key (location_id));
create table parking_lot (parking_lot_id integer generated by default as identity, location_id integer, parking_lot_code varchar(255), parking_rate double not null, primary key (parking_lot_id));
create table parking_position (position_id integer generated by default as identity, position_code varchar(255), parking_lot_id integer, primary key (position_id));
alter table parking_lot add constraint FKcpbf9svd1d5ibhugqc8n9xsq6 foreign key (location_id) references location;
alter table parking_position add constraint FKaffughhw6umw06j8t0sh7x53a foreign key (parking_lot_id) references parking_lot;